minor fixes

diff --git a/rust/Dockerfile b/rust/Dockerfile
--- a/rust/Dockerfile
+++ b/rust/Dockerfile
@@ -40,9 +40,15 @@ RUN cargo chef cook --release --recipe-path recipe.json
 # ------------------------------------------------------
 FROM chef AS builder
 WORKDIR /app
+
 ARG SERVICE_NAME
-# Fail the build if no service name is provided
+# Fail the build if no SERVICE_NAME is provided
 RUN test -n "$SERVICE_NAME" || (echo "⚠️ SERVICE_NAME argument not set" && false)
+
+# sqlx need to perform compile time check
+ARG DATABASE_URL
+# Fail the build if no DATABASE_URL is provided
+RUN test -n "$DATABASE_URL" || (echo "⚠️ DATABASE_URL argument not set" && false)
 
 # Copy cached dependencies
 COPY --from=cacher /app/target target
